app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import register

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # главная страница сайта
    path('', include('core.urls')),
    # магазин
    path('store/', include('store.urls')),
    # сообщество - создание и просмотр постов
    path('community/', include('community.urls')),
    # покупка абонементов
    path('membership/', include('membership.urls')),


    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register, name='register'),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/store/urls.py
from django.urls import path

from store.views import *

app_name = 'store_app'

urlpatterns = [
    # главная страница магазина
    path('', store, name="store"),
    # страница, которая отображает содержимое страницы
    path('cart/', cart, name="cart"),
    # страница оформления заказа
    path('checkout/', checkout, name="checkout"),
    # ссылка на контроллер, который обрабатывает данные, полученные из функции "updateUserOrder" из файла cart.js
    path('update_item/', update_item, name="update_item"),
    #  ссылка на контроллер, который обрабатывает данные, полученные из функции "submitFormData" script checkout.html
    path('process_order/', process_order, name="process_order"),
    #
    path('my_orders/<int:order_id>/', my_orders, name='my_orders'),
    #
    path('purchase_archive/', purchase_archive, name='purchase_archive'),

]

app/store/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

    # Исключение ошибки ValueError при формировании страницы
    # если изображение отсутствует, то ссылка на него будет пустой строкой, страница сформируется
    @property
    def image_url(self):
        try:
            url = self.image.url
        except ValueError:
            url = ''
        return url


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        order_items = self.orderitem_set.all()
        for i in order_items:
            if not i.product.digital:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        order_items = self.orderitem_set.all()
        total = sum([item.get_total for item in order_items])
        return total

    @property
    def get_cart_items(self):
        order_items = self.orderitem_set.all()
        total = sum([item.quantity for item in order_items])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

app/store/views.py
from django.shortcuts import render, get_object_or_404
from store.models import *
from django.http import JsonResponse
import json
import datetime
from store.utils import cart_data, guest_order


def store(request):
    data = cart_data(request)
    cart_items = data['cart_items']

    products = Product.objects.all()
    context = {'products': products, "cart_items": cart_items}
    return render(request, 'store/store.html', context)


def cart(request):

    data = cart_data(request)
    cart_items = data['cart_items']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cart_items': cart_items}
    return render(request, 'store/cart.html', context)


def checkout(request):

    data = cart_data(request)
    cart_items = data['cart_items']
    order = data['order']
    items = data['items']

    context = {'items': items, 'order': order, 'cart_items': cart_items}
    return render(request, 'store/checkout.html', context)


# Получаем данные из функции JS updateUserOrder.
# Если нет экземпляра модели 'Order', то создается новый.
# На основе полученных данных создаем экземпляры модели 'OrderItem'.
def update_item(request):
    data = json.loads(request.body)
    product_id = data['product_id']
    action = data['action']

    customer = request.user.customer
    product = Product.objects.get(id=product_id)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    order_item, created = OrderItem.objects.get_or_create(order=order, product=product)

    # изменение значений в поле 'quantity' модели 'OrderItem'
    if action == 'add':
        order_item.quantity = (order_item.quantity + 1)
    elif action == 'remove':
        order_item.quantity = (order_item.quantity - 1)
    order_item.save()
    if order_item.quantity <= 0:
        order_item.delete()
    return JsonResponse('Item was added!', safe=False)


# Получаем данные из функции JS submitFormData.
def process_order(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)

    else:
        customer, order = guest_order(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == float(order.get_cart_total):
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )

    print('Data', request.body)
    print(transaction_id)

    return JsonResponse('Payment complete', safe=False)


def my_orders(request, order_id):
    data = cart_data(request)
    cart_items = data['cart_items']

    customer = request.user.customer
    order = Order.objects.filter(customer=customer, complete=True)
    items = OrderItem.objects.filter(order__customer=customer)

    order_item = get_object_or_404(Order, pk=order_id, customer=customer)
    context = {'order_item': order_item, 'order': order, 'cart_items': cart_items, 'items': items}
    return render(request, 'store/my_orders.html', context)


def purchase_archive(request):
    data = cart_data(request)
    cart_items = data['cart_items']

    customer = request.user.customer
    order = Order.objects.filter(customer=customer, complete=True).order_by('-date_ordered')
    items = OrderItem.objects.filter(order__customer=customer)

    context = {'order': order, 'cart_items': cart_items, 'items': items}
    return render(request, 'store/purchase_archive.html', context)

app/store/templates/store/cart.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-dark" href="{% url 'store_app:store' %}">&#x2190; Continue Shopping </a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{ order.get_cart_items }}</strong></h5></th>
						<th><h5>Total:<strong> ${{ order.get_cart_total|floatformat:2 }}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'store_app:checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>

                {% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{ item.product.image_url }}"></div>
					<div style="flex:2"><p>{{ item.product.name }}</p></div>
					<div style="flex:1"><p>${{ item.product.price| floatformat:2 }}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product="{{item.product.id}}" data-action="add"
                                 class="chg-quantity update-cart" src="{% static  'img/arrow-up.png' %}">

							<img data-product="{{item.product.id}}" data-action="remove"
                                 class="chg-quantity update-cart" src="{% static  'img/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>${{ item.get_total }}</p></div>
				</div>
                {% endfor %}
			</div>
		</div>
	</div>


{% endblock content %}

app/store/templates/store/checkout.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
     <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
                    {% csrf_token %}
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>

					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
				<small>Paypal Options</small>
				<button id="make-payment">Make payment</button>
{#				<div id="paypal-button-container"></div>#}
			</div>

		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'store_app:cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.image_url}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
					<div style="flex:1"><p>x{{item.quantity}}</p></div>
				</div>
				{% endfor %}
				<h5>Items:   {{order.get_cart_items}}</h5>
				<h5>Total:   ${{order.get_cart_total|floatformat:2}}</h5>
			</div>
		</div>
	</div>


    <script type="text/javascript">
        var shipping = '{{order.shipping}}'
		var total = '{{order.get_cart_total}}'

        if (shipping === 'False'){
            document.getElementById('shipping-info').innerHTML = ''
        }
        if (user !== 'AnonymousUser'){
		 	document.getElementById('user-info').innerHTML = ''
		 }

		if (shipping === 'False' && user !== 'AnonymousUser'){
			//Hide entire form if user is logged in and shipping is false
				document.getElementById('form-wrapper').classList.add("hidden");
				//Show payment if logged in user wants to buy an item that does not require shipping
			    document.getElementById('payment-info').classList.remove("hidden");
		}


        var form = document.getElementById('form')
		form.addEventListener('submit', function(e){
	    	e.preventDefault()
	    	console.log('Form Submitted...')
	    	document.getElementById('form-button').classList.add("hidden");
	    	document.getElementById('payment-info').classList.remove("hidden");
	    })

	    document.getElementById('make-payment').addEventListener('click', function(e){
	    	submitFormData()
	    })

        function submitFormData() {
            console.log('Payment button clicked')

        var userFormData = {
				'name':null,
				'email':null,
				'total':total,
			}

			var shippingInfo = {
				'address':null,
				'city':null,
				'state':null,
				'zipcode':null,
			}

			if (shipping !== 'False'){
	    		shippingInfo.address = form.address.value
		    	shippingInfo.city = form.city.value
		    	shippingInfo.state = form.state.value
		    	shippingInfo.zipcode = form.zipcode.value
	    	}

	    	if (user === 'AnonymousUser'){
	    		userFormData.name = form.name.value
	    		userFormData.email = form.email.value
	    	}

	    	console.log('Shipping Info:', shippingInfo)
	    	console.log('User Info:', userFormData)

            var url = "/store/process_order/"
	    	fetch(url, {
	    		method:'POST',
	    		headers:{
	    			'Content-Type':'applicaiton/json',
	    			'X-CSRFToken':csrftoken,
	    		},
	    		body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo}),

	    	})
	    	.then((response) => response.json())
     		//data - ответ сервера после POST запроса на url = "/store/process_order/"
			// пример:  return JsonResponse('Payment complete', safe=False)
	    	.then((data) => {
				console.log('Success:', data);
				alert('Transaction completed');

            cart = {}
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
				window.location.href = "{% url 'store_app:store' %}"
				})

        }

    </script>



{% endblock content %}

app/store/templates/store/my_orders.html
{% extends 'core/profile.html' %}
{% load static %}



{% block profile %}
           <h1> Сведения о покупке </h1>

<hr>

            <a  class="btn btn-outline-dark" href="{% url 'store_app:purchase_archive'  %}">
                Вернуться в архив покупок
            </a>
<hr>


  <p> Номер заказа: {{ order_item.pk }} </p>
  <p> Имя пользователя: {{ order_item.customer }}</p>
  <p> Дата заказа : {{ order_item.date_ordered | date:"d.m.Y H:i:s" }} </p>
  <p> Общая сумма заказа : $ {{ order_item.get_cart_total }} </p>

    <hr>

<div class="box-element">
				<div class="cart-row">
                    <div style="flex:2"> <strong> Item</strong> </div>
					<div style="flex:2"><strong>Image</strong></div>

					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
				</div>

                {% for item in order_item.orderitem_set.all %}

				<div class="cart-row">
    				<div style="flex:2"><p>{{ item.product.name }}</p></div>
					<div style="flex:2"><img class="row-image" src="{{ item.product.image_url }}"></div>

					<div style="flex:1"><p>${{ item.product.price| floatformat:2 }}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>

					</div>

				</div>
                {% endfor %}
			</div>

<hr>



{% endblock %}

app/store/templates/store/purchase_archive.html
{% extends 'core/profile.html' %}
{% load static %}



{% block profile %}
 <h1> Архив покупок </h1>

  {% for item in order %}
           <a  class="btn btn-outline-dark count"  href="{% url 'store_app:my_orders' item.id  %}">
               | Заказ: {{ item.id }} от {{ item.date_ordered | date:"d.m.Y" }}
            </a>
  {% endfor %}
{% endblock %}

app/store/templates/store/store.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
	<div class="row">
        {% for product in products %}
		<div class="col-lg-4">
            <img  class="thumbnail" src="{{product.image_url}}">
			<div class="box-element product">
                <h6> <strong> {{ product.name }}</strong></h6>
                <hr>
				<button data-product="{{ product.id }}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
				<a class="btn btn-outline-success" href="#">View</a>
				<h4 style="display: inline-block; float: right"><strong>
                    $ {{ product.price|floatformat:2 }}</strong></h4>
			</div>
		</div>
       {% endfor %}
    </div>


{% endblock content %}