app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import register

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # главная страница сайта
    path('', include('core.urls')),
    # магазин
    path('store/', include('store.urls')),
    # сообщество - создание и просмотр постов
    path('community/', include('community.urls')),
    # покупка абонементов
    path('membership/', include('membership.urls')),


    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register, name='register'),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/community/urls.py
from django.urls import path

from community.views import *

app_name = 'community'

urlpatterns = [
    # главная страница fitlife community
    path('', main_page, name="main_page"),
    path('tags/<slug:tag_slug>/', TagIndexView.as_view(), name='post_by_tag'),
    path('post_detail/<post_pk>/', post_detail, name='post_detail'),
    path('create_post/', CreatePost.as_view(), name='create_post'),
    path('my_posts/', my_posts, name='my_posts'),
    path('delete_comment/<comm_pk>/', delete_comment, name='delete_comment'),
    path('delete_post/<post_pk>/', delete_post, name='delete_post'),
    path('edit_post/<int:pk>/', UpdatePost.as_view(), name='edit_post'),
    ]

app/community/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from taggit.managers import TaggableManager
from taggit.models import TagBase, GenericTaggedItemBase

from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

import re
from transliterate import slugify


class MyCustomTag(TagBase):
    # ... fields here

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")

    # ... methods (if any) here
    # переопределяю метод slugify
    def slugify(self, tag, i=None):
        # tag - <class 'str'>
        # преобразовываю <class 'str'> в <class 'list'>
        words = tag.split()
        # компилирую объекты регулярного выражения для последующего использования
        r1 = re.compile("[а-яА-Я]+")
        r2 = re.compile("[a-zA-Z]+")
        # ищу соответствие шаблону в начале строки и формирую два списка
        # слова написанные на кирилице и слова неаписанные латинскими символами.
        words_rus = [w for w in filter(r1.match, words)]
        words_eng = [w for w in filter(r2.match, words)]
        # преобразую список написанный на кирилице в латинские символы
        words_rus_to_eng = []
        for i in words_rus:
            words_rus_to_eng.append(slugify(i))
        # формирую окончательный список слов написанных латинскими символами
        words_final = words_eng + words_rus_to_eng
        # преобразовываю <class 'list'> в  <class 'str'>
        words_final_1 = ', '.join(words_final)
        slug = words_final_1
        return slug


class TaggedWhatever(GenericTaggedItemBase):
    # TaggedWhatever can also extend TaggedItemBase or a combination of
    # both TaggedItemBase and GenericTaggedItemBase. GenericTaggedItemBase
    # allows using the same tag for different kinds of objects, in this
    # example Food and Drink.

    # Here is where you provide your custom Tag class.
    tag = models.ForeignKey(
        MyCustomTag,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )


class Comment(models.Model):
    class Meta:
        ordering = ['-created']

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='post')

    def __str__(self):
        return self.text


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    text = models.TextField()
    image = models.ImageField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    tags = TaggableManager(through=TaggedWhatever)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('community:post_detail', kwargs={'post_pk': self.pk})

app/community/forms.py
from django import forms
from community.models import Post
from taggit.forms import TagWidget


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'image', 'tags']
        exclude = ('author',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'tags': TagWidget(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            # важно при загрузке изображения!!!
            'image': forms.FileInput(attrs={'class': 'input-image-control'})
        }


# add comment form
class AddCommentForm(forms.Form):
    text = forms.CharField(label="Введите комментарий", widget=forms.TextInput(attrs={'class': 'form-control'}))

app/community/views.py
from django.shortcuts import render, redirect
from community.models import *
from django.views.generic import ListView, CreateView, UpdateView
from community.forms import PostForm, AddCommentForm
from django.urls import reverse_lazy
from django.http import HttpResponse


def main_page(request):
    post = Post.objects.all().order_by('-created')
    context = {'post': post}
    return render(request, 'community/comm_main_page.html', context)


# tag index view
class TagIndexView(ListView):
    model = Post
    template_name = 'community/comm_main_page.html'
    context_object_name = 'post'

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs.get('tag_slug')).order_by('-created')


# post detail
def post_detail(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    author = request.user
    # форма для добавления комментариев
    if request.method == 'POST':
        form = AddCommentForm(request.POST)
        if form.is_valid():
            Comment.objects.create(
                author=author, post=post, text=form.cleaned_data["text"]
            )
            form = AddCommentForm()
            pass
    else:
        form = AddCommentForm()
    return render(request, 'community/post_detail.html', {'post': post, 'form': form})


class CreatePost(CreateView):
    form_class = PostForm
    template_name = 'community/create_post.html'
    success_url = reverse_lazy('community:main_page')
    raise_exception = True

    # добавляет в поле автор id текущего юзера автоматически
    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(CreatePost, self).form_valid(form)


class UpdatePost(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'community/update_post.html'
    success_url = reverse_lazy('community:main_page')
    raise_exception = True

    # добавляет в поле автор id текущего юзера автоматически
    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(UpdatePost, self).form_valid(form)


def delete_post(request, post_pk):
    # active_user = News.objects.get(author_id=request.user.pk)
    Post.objects.get(author_id=request.user.pk, id=post_pk).delete()
    return redirect('community:my_posts')


def my_posts(request):
    post = Post.objects.filter(author=request.user)
    context = {'post': post}
    return render(request, 'community/my_posts.html', context)


# удаление коментария по id. Может удалить только тот кто написал комментарий.
def delete_comment(request, comm_pk):
    author = request.user
    # получаем коментарий
    comment = Comment.objects.get(id=comm_pk)
    # получаем пост по ID через поле в связанной таблице (comment.post_id)
    object = Post.objects.get(id=comment.post_id)
    try:
        Comment.objects.get(id=comm_pk, author=author).delete()
    except:
        # если пост попытается удалить не автор, то возникнет исключение
        return HttpResponse("No permission")
    # Передавая объект; в качестве URL-а для перенаправления
    # будет использоваться результат вызова метода get_absolute_url()
    return redirect(object)



# # create post
# def create_post(request):
#     if request.method == "POST":
#         form = PostForm(request.POST)
#         if form.is_valid():
#             #  logger.info(form.cleaned_data)
#             # unpacking the dictionary and assigning values from the received data to the model
#             # author=request.user - will be added automatically
#             Post.objects.create(**form.cleaned_data, author=request.user)
#             return redirect('community:main_page')
#
#     else:
#         form = PostForm()
#     post = 'qqq'
#     return render(request, 'community/create_post.html', {'post': post, 'form': form})

app/community/templates/community/comm_main_page.html
{% extends 'main.html' %}
{% load static %}

   {% block content %}


    <!-- Start Featured Product -->
    <section>
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-6 m-auto">
                    <h1 class="h2">Fitlife community</h1>
                    <p>
                        Здесь Вы можете делиться своими тренировками, личными достижениями, планами питания и просто хорошими
                        и интересными событиями из мира спорта с остальными участниками сообщества!
                    </p>

                </div>
            </div>

        </div>
    </section>
    <!-- End Featured Product -->






    <!-- Start Content -->

    <div class="container">
        <div class="row">

            <div class="col-lg-2">
                <h1 class="h2 pb-4">Tags: </h1>

              {% for tag in most_comm_tags %}
              <a class="btn btn-outline-success" href="{% url 'community:post_by_tag' tag.slug %}" role="button">{{ tag.name }}</a>
               {% endfor %}

                <hr>
                <a  class="btn btn-outline-secondary" href="{% url 'community:main_page' %}"> Показать все посты </a>
                <hr>

                <a  class="btn btn-outline-secondary" href="{% url 'community:create_post' %}"> Создать пост </a>

                <hr>
                <a  class="btn btn-outline-secondary" href="{% url 'community:my_posts' %}"> Перейти в мои посты </a>
            </div>


            <div class="col-lg-10">
                <div class="row">

            {% for item in post %}
                    <div class="col-md-4">
                        <div class="card mb-4 product-wap rounded-0">
                            <div class="card-body" style="height: 102px">
                                 <p> {{ item.title }} </p>
                            </div>
                            <div class="card rounded-0">

                                {% if item.image %}
                                <img class="thumbnail" src="{{ item.image.url }}">
                                {% else %}
                                <img class="thumbnail" src="{% static '/img/no-image-available.jpg' %}">
                                {% endif %}
                            </div>
                            <div class="card-body" style="height: 159px">
                                 <p> {{ item.text|safe|linebreaks|truncatewords:"5" }}</p>
                         <a  class="btn btn-outline-secondary" href="{{ item.get_absolute_url }}"> Читать далее </a>
                            </div>
                            <div class="card-body"style="height: 200px">
                                 <p> <strong>Author: </strong> {{ item.author }} </p>
                                <p> <strong>Date:  </strong> {{ item.created | date:"d-m-Y H:i:s" }} </p>
                                 <p> <strong>Tags: </strong>
                                  {% for tag in item.tags.all %}
                                        <a class="btn btn-outline-success" href="{% url 'community:post_by_tag' tag.slug %}" role="button">{{ tag.name }}</a>
                                  {% endfor %}

                                 </p>
                            </div>
                        </div>
                    </div>
            {% endfor %}

                </div>
            </div>
        </div>
    </div>

    <!-- End Content -->


  {% endblock content %}

app/community/templates/community/create_post.html
{% extends 'core/profile.html' %}
{% load static %}



{% block profile %}
    <div class="container">
        <div class="row">

            <div class="col-lg-10">
                <div style="padding: 20px">

                            <h1 class="h2">Добавить новый пост</h1>
                                {#    указать при загрузке изображения enctype="multipart/form-data" #}
                                <form action="{% url 'community:create_post' %}" method="post" enctype="multipart/form-data" >
                                {% csrf_token %}

                                {{ form.as_p }}
                                  <button type="submit" class=" btn-outline-success form-control"> Добавить пост</button>

                                </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

app/community/templates/community/my_posts.html
{% extends 'core/profile.html' %}
{% load static %}



{% block profile %}
     <div class="box-element">
               <div class="cart-row">
					<div style="flex:1.4"><strong>Изображение</strong></div>
					<div style="flex:2"><strong style="margin-left:10px">Название</strong></div>
					<div style="flex:2"><strong>Дата добавления</strong></div>
                   	<div style="flex:2"><strong>Редактировать</strong></div>
                  	<div style="flex:2"><strong>Удалить</strong></div>
				</div>

                    {% for item in post %}
				<div class="cart-row" >

                {% if item.image %}
 					<div style="flex:1.4"><img class="row-image" src="{{ item.image.url }}" style="margin-top: 8px; margin-left:10px"></div>
               {% else %}
 					<div style="flex:1.4"><img class="row-image" src="{% static '/img/no-image-available.jpg' %}" style="margin-top: 8px; margin-left:10px"></div>
               {% endif %}
					<div style="flex:2"><a class="text-decoration-none text-secondary" href="{{ item.get_absolute_url }}">{{ item.title }}</a></div>
					<div style="flex:2"><p>{{ item.created | date:'Y.m.d  H:m' }}</p></div>
                    <div style="flex:2"><p></p><a  class="btn btn-outline-success" href="{% url 'community:edit_post' pk=item.pk %}"> Редактировать пост </a></div>
                    <div style="flex:2"><p></p><a  class="btn btn-outline-danger" href="{% url 'community:delete_post' item.pk %}"> Удалить пост </a></div>



				</div>
                {% endfor %}
     </div>


{% endblock %}

app/community/templates/community/post_detail.html
{% extends 'main.html' %}
{% load static %}

   {% block content %}


    <!-- Start Featured Product -->
    <section>
        <div class="container py-2">
            <div class="row text-center py-3">
                <div class="col-lg-6 m-auto">
                    <h1 class="h1">Fitlife community</h1>
                    <p>
                        Здесь Вы можете делиться своими тренировками, личными достижениями, планами питания и просто хорошими
                        и интересными событиями из мира спорта с остальными участниками сообщества!
                    </p>
                    <a  class="btn btn-outline-secondary" href="{% url 'community:main_page' %}"> Вернуться в Fitlife community </a>
                    <a  class="btn btn-outline-secondary" href="{% url 'community:my_posts' %}"> Перейти в мои посты </a>

                </div>
            </div>

        </div>
    </section>
    <!-- End Featured Product -->






    <!-- Start Content -->

    <div class="container">
        <div class="row">

            <div class="col-lg-2">
                <h1 class="h2 pb-4">Tags: </h1>

              {% for tag in most_comm_tags %}
              <a class="btn btn-outline-success" href="{% url 'community:post_by_tag' tag.slug %}" role="button">{{ tag.name }}</a>
               {% endfor %}

                <hr>
                <a  class="btn btn-outline-secondary" href="{% url 'community:main_page' %}"> Показать все посты </a>
                <hr>
               <a  class="btn btn-outline-secondary" href="{% url 'community:create_post' %}"> Создать пост </a>
            </div>


            <div class="col-lg-10">
                <div class="row">


                    <div>
                        <div class="card mb-4 product-wap rounded-0">
                            <div class="card-body">
                                 <p> <strong> Title: </strong> {{ post.title }} </p>
                            </div>
                            <div class="card rounded-0">

                                {% if post.image %}
                                <img class="card-img rounded-0 img-fluid" src="{{ post.image.url }}">
                                {% else %}
                                <img class="card-img rounded-0 img-fluid" src="{% static '/img/no-image-available.jpg' %}">
                                {% endif %}
                            </div>
                            <div class="card-body">
                                 <p> {{ post.text }}</p>
                                       </div>
                            <div class="card-body">
                                 <p> <strong>Author: </strong> {{ post.author }} </p>
                                <p> <strong>Date:  </strong> {{ post.created | date:"d-m-Y H:i:s" }} </p>
                                 <p> <strong>Tags: </strong>
                                  {% for tag in post.tags.all %}
                                        <a class="btn btn-outline-success" href="{% url 'community:post_by_tag' tag.slug %}" role="button">{{ tag.name }}</a>
                                  {% endfor %}

                            {% if post.post.all %}

                                    <h5> Comments: </h5>
                                  {% for comm in post.post.all %}
                                      {{ comm.author }} || {{ comm.created | date:"d-m-Y H:i:s" }} || Time has passed: {{ comm.created | timesince }}
                                      <h6>{{ comm.text }}</h6>
                                      <h6>id коментария - {{ comm.pk }}</h6>

                                      {# кнопка видна только для автора коментария#}
                                      {% if user.is_authenticated and user == comm.author %}
                                      <a href="{% url 'community:delete_comment' comm.pk %}"> <button class="btn btn-outline-danger"> DELETE Comment</button></a>
                                      {% endif %}
                                      <hr>

                                  {% endfor %}

                            {% else %}
                                <h3> No comments</h3>
                            {% endif %}

                                {#  коментарии могут оставлять только авторизированные пользователи #}
                                {% if user.is_authenticated %}
                                 <form method="post">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                        <button type="submit" class=" btn btn-outline-success"> Add comment</button>
                                </form>
                                {% endif %}

                                 </p>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>

    <!-- End Content -->


  {% endblock content %}

app/community/templates/community/update_post.html
{% extends 'core/profile.html' %}
{% load static %}



{% block profile %}
    <div class="container">
        <div class="row">

            <div class="col-lg-10">
                <div style="padding: 20px">

                            <h1 class="h2">Редактировать  пост</h1>
                                {#    указать при загрузке изображения enctype="multipart/form-data" #}
                                <form action="{% url 'community:edit_post' pk=post.pk %}" method="post" enctype="multipart/form-data" >
                                {% csrf_token %}

                                {{ form.as_p }}
                                  <button type="submit" class=" btn-outline-success form-control"> Добавить пост</button>

                                </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}