app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import register

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # главная страница сайта
    path('', include('core.urls')),
    # магазин
    path('store/', include('store.urls')),
    # сообщество - создание и просмотр постов
    path('community/', include('community.urls')),
    # покупка абонементов
    path('membership/', include('membership.urls')),


    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register, name='register'),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [

    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('profile/', profile, name='profile'),
    path('tariffs/', tariffs, name='tariffs'),
    path('our_command/', our_command, name='our_command'),

]

app/membership/urls.py
from django.urls import path
from membership.views import *

app_name = 'membership'

urlpatterns = [

    # path('', index, name='index'),
    path('my_subscription/', my_subscription, name='my_subscription'),
    path('add_membership/<item_pk>/', add_membership, name='add_membership'),
    path('activation/<item_pk>/', activation, name='activation'),
    # path('deactivation/<item_pk>/', deactivation, name='deactivation'),
    path('delete_membership/<item_pk>/', delete_membership, name='delete_membership'),
    path('check_visit/<item_pk>/', check_visit, name='check_visit'),
]

app/community/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from taggit.managers import TaggableManager
from taggit.models import TagBase, GenericTaggedItemBase

from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

import re
from transliterate import slugify


class MyCustomTag(TagBase):
    # ... fields here

    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")

    # ... methods (if any) here
    # переопределяю метод slugify
    def slugify(self, tag, i=None):
        # tag - <class 'str'>
        # преобразовываю <class 'str'> в <class 'list'>
        words = tag.split()
        # компилирую объекты регулярного выражения для последующего использования
        r1 = re.compile("[а-яА-Я]+")
        r2 = re.compile("[a-zA-Z]+")
        # ищу соответствие шаблону в начале строки и формирую два списка
        # слова написанные на кирилице и слова неаписанные латинскими символами.
        words_rus = [w for w in filter(r1.match, words)]
        words_eng = [w for w in filter(r2.match, words)]
        # преобразую список написанный на кирилице в латинские символы
        words_rus_to_eng = []
        for i in words_rus:
            words_rus_to_eng.append(slugify(i))
        # формирую окончательный список слов написанных латинскими символами
        words_final = words_eng + words_rus_to_eng
        # преобразовываю <class 'list'> в  <class 'str'>
        words_final_1 = ', '.join(words_final)
        slug = words_final_1
        return slug


class TaggedWhatever(GenericTaggedItemBase):
    # TaggedWhatever can also extend TaggedItemBase or a combination of
    # both TaggedItemBase and GenericTaggedItemBase. GenericTaggedItemBase
    # allows using the same tag for different kinds of objects, in this
    # example Food and Drink.

    # Here is where you provide your custom Tag class.
    tag = models.ForeignKey(
        MyCustomTag,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )


class Comment(models.Model):
    class Meta:
        ordering = ['-created']

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='post')

    def __str__(self):
        return self.text


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    text = models.TextField()
    image = models.ImageField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    tags = TaggableManager(through=TaggedWhatever)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('community:post_detail', kwargs={'post_pk': self.pk})

app/core/models.py
from django.db import models

# Create your models here.

app/core/views.py
from django.shortcuts import render, redirect
from store.models import *
from membership.models import Membership, Subscription
from store.utils import cart_data
from app.forms import UserRegisterForm
from django.contrib.auth import login



# Главная страница проекта
def index(request):
    # объект cartItems нужен для отображения количества товаров в корзине на главной странице
    data = cart_data(request)
    cart_items = data['cart_items']
    subscription = Subscription.objects.all()[:3]
    context = {
        "cart_items": cart_items,
        "subscription": subscription
    }
    return render(request, 'core/index.html', context)



# информация о сайте
def about(request):
    # объект cartItems нужен для отображения количества товаров в корзине на главной странице
    data = cart_data(request)
    cart_items = data['cart_items']
    context = {"cart_items": cart_items}
    return render(request, 'core/about.html', context)


# контакты
def contact(request):
    # объект cartItems нужен для отображения количества товаров в корзине на главной странице
    data = cart_data(request)
    cart_items = data['cart_items']
    context = {"cart_items": cart_items}
    return render(request, 'core/contact.html', context)


# тарифы
def tariffs(request):
    # объект cartItems нужен для отображения количества товаров в корзине на главной странице
    data = cart_data(request)
    cart_items = data['cart_items']
    subscription = Subscription.objects.all()
    context = {
        "cart_items": cart_items,
        "subscription": subscription

    }
    return render(request, 'core/tariffs.html', context)


def profile(request):
    data = cart_data(request)
    cart_items = data['cart_items']

    customer = request.user.customer
    order = Order.objects.filter(customer=customer, complete=True).order_by('-date_ordered')
    items = OrderItem.objects.filter(order__customer=customer)

    context = {'order': order, 'cart_items': cart_items, 'items': items}
    return render(request, 'core/profile.html', context)


# регистрация нового пользователя
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # одновременное автоматическое создание объекта Customer, для совершения покупок
            Customer.objects.create(user=request.user,
                                    name=form.cleaned_data.get('username'),
                                    email=form.cleaned_data.get('email'))
            Membership.objects.create(user=request.user,
                                      name=form.cleaned_data.get('username'),
                                      email=form.cleaned_data.get('email'))

            return redirect('core:index')
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})



# информация о команде
def our_command(request):
    # объект cartItems нужен для отображения количества товаров в корзине на главной странице
    data = cart_data(request)
    cart_items = data['cart_items']
    context = {"cart_items": cart_items}
    return render(request, 'core/our_command.html', context)

app/core/templates/core/about.html
{% extends 'main.html' %}
{% load static %}

   {% block content %}




    <div class="row py-lg-5 text-center">
      <div class=" col-md-8 mx-auto">
        <h1 class="font-weight-light">Информация о клубе</h1>
        <p class="lead">

                    Клуб занимает двухуровневое пространство площадью 8 000 квадратных метров.
        На первом уровне разместились бассейн с джакузи, хамамом и соляной пещерой, раздевалки,
        студия GYROTONIC зал единоборств, сайкл студия, салон красоты с банным комплексом, кафе,
        а также залы для детского фитнеса — со своим бассейном и хамамом.
        Второй уровень занимают тренажерный зал, большой и малый залы для групповых программ,
        фитнес-бар, зона функционального тренинга,
        теннисные корты, мини-футбольное поле, зона для стретчинга и кардиозанятий.

        </p>
                    <div style="flex:2"><a  class="btn btn-outline-success" href="{% url 'core:tariffs' %}"> Купить абонемент </a>
                    </div>

      </div>
    </div>


    <!-- Close Banner -->

<div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
           <img class="bd-placeholder-img card-img-top" width="100%" height="225"  src="{% static 'img/about_1.jpg' %}">
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
           <img class="bd-placeholder-img card-img-top" width="100%" height="225"  src="{% static 'img/about_2.jpg' %}">
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
           <img class="bd-placeholder-img card-img-top" width="100%" height="225"  src="{% static 'img/about_3.jpg' %}">
          </div>
        </div>

      </div>
    </div>
  </div>



  {% endblock content %}

app/core/templates/core/contact.html
{% extends 'main.html' %}
{% load static %}

   {% block content %}

    <!-- Start Content Page -->
    <div class="container-fluid" style="padding: 2rem">
        <div class="col-md-6 m-auto text-center">
            <h1 class="h1">Contact Us</h1>

                    <h2 class="h2 text-success border-bottom pb-3  logo">Fitlife company</h2>

                    <ul class="list-unstyled footer-link-list">
                        <li>
                        <i class="fas fa-map-marker-alt fa-fw"></i>
                            123 Consectetur at ligula 10660
                        </li>
                        <li>
                            <i class="fa fa-phone fa-fw"></i>
                            <a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-fw"></i>
                            <a class="text-decoration-none" href="mailto:info@company.com">fitlife@company.com</a>
                        </li>
                    </ul>

        </div>
    </div>




  {% endblock content %}

app/core/templates/core/index.html
{% extends 'main.html' %}
{% load static %}

   {% block content %}
{#<div class="card">#}
{#<img src="{% static 'store/img/walpaper.jpg' %}" height="240" >#}
{#</div>#}

{#<div class="card mb-3 text-center">#}
{#      <h1 class="display-4 font-italic ">Фитнес в контексте жизни!</h1>#}
{#      <p class="lead my-3">В этом разделе будет описание фитнес центра,#}
{#          основные услуги, адреса, новости и еще много полезной информации....</p>#}
{#       <p>  <a class="btn btn-light" href="{% url 'about' %}" style="margin-left: 3px"> Продолжить чтение </a></p>#}
{#</div>#}


<hr>
<!-- Start Banner Hero -->
    <div id="template-mo-zay-hero-carousel" class="carousel slide" data-bs-ride="carousel">
        <ol class="carousel-indicators">
            <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="0" class="active"></li>
            <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="1"></li>
            <li data-bs-target="#template-mo-zay-hero-carousel" data-bs-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="container">
                    <div class="row p-5">
                        <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid" src="{% static 'img/fitness_main_page_1.jpg' %}" alt="">
                        </div>
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-left align-self-center">
                                <h1 class="h1 text-success"><b>Fitlife </b> Современный фитнес центр</h1>

                                <p>
                        Приглашаем всех, кто хочет присоединиться к числу наших довольных клиентов,
                        в фитнес центр «Fitlife» прямо в центре столицы.
                        Здесь Вас ждут профессионально составленные программы занятий на любой вкус.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container">
                    <div class="row p-5">
                        <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid" src="{% static 'img/fitness_main_page_2.jpg' %}" alt="">
                        </div>
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-left">
                                <h1 class="h1">Работаем круглосуточно.</h1>
                                <h3 class="h2">Тренируйся в любое удобное для тебя время.</h3>
                                <p>
                               У нас нет ограничений по возрасту в разумных пределах.
                                У нас удобный график работы! Приходите с 07.00 до 24.00 по будням и с 09.00 до 22.00 по выходным и праздникам.
                                <strong> Мы Вам рады!</strong>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="container">
                    <div class="row p-5">
                        <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                            <img class="img-fluid" src="{% static 'img/fitness_main_page_3.jpg' %}" alt="">
                        </div>
                        <div class="col-lg-6 mb-0 d-flex align-items-center">
                            <div class="text-align-left">
                                <h1 class="h1">Современные тренажеры.</h1>
                                <h3 class="h2">Путь к идеальной форме.</h3>
                                <p>
                Тренировки проводятся в залах, оборудованных в соответствии
                с требованиями безопасности и современными стандартами.
                Попробуйте свои силы на разных снарядах, которые позволят развить каждую группу мышц организма
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev text-decoration-none w-auto ps-3" href="#template-mo-zay-hero-carousel" role="button" data-bs-slide="prev">
            <i class="fas fa-chevron-left"></i>
        </a>
        <a class="carousel-control-next text-decoration-none w-auto pe-3" href="#template-mo-zay-hero-carousel" role="button" data-bs-slide="next">
            <i class="fas fa-chevron-right"></i>
        </a>
    </div>
    <!-- End Banner Hero -->

<hr>



    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Покупка  абонемента</h1>
    <p class="lead"> Цены на абонементы для посещения тренажерного зала</p>
    <hr>
    </div>

            <div class="col-lg-10 container-fluid">
                <div class="row">

            {% for item in subscription %}
                    <div class="col-md-4">
                        <div class="card mb-4 product-wap rounded-0">
                            <div class="card-body" style="height: 102px">
                                 <p> {{ item.get_title_display }} </p>
                            </div>


                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal"> {{ item.description }} </h4>
                            </div>
                            <div class="card-body">
                                <h1 class="card-title pricing-card-title"><span>&#8381;</span> {{ item.price }} </h1>
                                <ul class="list-unstyled mt-3 mb-4">
                                </ul>

                                         {% if request.user.is_authenticated %}
                           <a href="{% url 'membership:add_membership' item.pk %}">
                               <button type="button" class="btn btn-sm btn-outline-secondary" > Купить </button>
                           </a>
                                <hr>
                                  {% else %}
                               <h2> Need registration to buy</h2>
                                  {% endif%}

                            </div>



                        </div>
                    </div>
            {% endfor %}

                </div>
            </div>

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

               <a href="{% url 'core:tariffs' %}">
                   <button type="button" class="btn btn-sm btn-outline-secondary" > Смотреть остальные тарифы </button>
               </a>
    <hr>
    </div>

  {% endblock content %}

app/core/templates/core/our_command.html
{% extends 'main.html' %}
{% load static %}

   {% block content %}

    <section class="our_command_color">
        <div class="container">
            <div class="row align-items-center py-1">
                <div class="col-md-12 text-black" style="padding: 1rem">
                    <h1 style="text-align: center">Информация о команде</h1>
                    <p style="text-align: center">
                      Мы команда профессионалов!
                     </p>

        <div class="row">
                    <div class="card" style="width: 25rem; margin: 10px">
                          <img src="{% static 'img/van_damme.jpg' %}" width="374" height="210" class="card-img-top">
                          <div class="card-body">
                            <h5 class="card-title">Jean-Claude Van Damme</h5>
                              <div class="staff-card__text">Элит-тренер тренажёрного зала<br />
                    <br />
                                  <strong> Образование и сертификаты: </strong><br />
                    <br />
                    ∙ Спортивная академия<br />
                    ∙ Сертифицированный тренер <br />
                    <br />

                                  <strong> Спортивные достижения: </strong><br />
                    <br />
                    ∙ Карате <br />
                    ∙ Кикбоксинг<br />

                    <br />
                                  <strong> Фитнес специализация:</strong><br />
                    <br />
                    ∙ снижение веса<br />
                    ∙ функциональный тренинг<br />
                          </div>

                          </div>
                        </div>

                    <div class="card" style="width: 25rem; margin: 10px;">
                          <img src="{% static 'img/bruce-lee.jpg' %}" width="374" height="210"  class="card-img-top">
                          <div class="card-body">
                            <h5 class="card-title">Bruce Lee</h5>
                              <div class="staff-card__text">Элит-тренер тренажёрного зала<br />
                    <br />
                                  <strong> Образование и сертификаты: </strong><br />
                    <br />
                    ∙ Спортивная академия<br />
                    ∙ Сертифицированный тренер <br />
                    <br />

                                  <strong> Спортивные достижения: </strong><br />
                    <br />
                    ∙ Карате <br />
                    ∙ Кикбоксинг<br />

                    <br />
                                  <strong> Фитнес специализация:</strong><br />
                    <br />
                    ∙ снижение веса<br />
                    ∙ функциональный тренинг<br />
                          </div>

                          </div>
                        </div>

                    <div class="card" style="width: 25rem; margin: 10px;">
                          <img src="{% static 'img/stallone.jpg' %}" width="374" height="210"  class="card-img-top">
                          <div class="card-body">
                            <h5 class="card-title">Sylvester Stallone</h5>
                              <div class="staff-card__text">Элит-тренер тренажёрного зала<br />
                    <br />
                                  <strong> Образование и сертификаты: </strong><br />
                    <br />
                    ∙ Спортивная академия<br />
                    ∙ Сертифицированный тренер <br />
                    <br />

                                  <strong> Спортивные достижения: </strong><br />
                    <br />
                    ∙ Карате <br />
                    ∙ Кикбоксинг<br />

                    <br />
                                  <strong> Фитнес специализация:</strong><br />
                    <br />
                    ∙ снижение веса<br />
                    ∙ функциональный тренинг<br />                          </div>

                          </div>
                        </div>
</div>











                </div>
            </div>
        </div>
    </section>
    <!-- Close Banner -->




  {% endblock content %}

app/core/templates/core/profile.html
{% extends 'main.html' %}
{% load static %}

{% block content %}


    <div class="container py-5">
        <div class="row">

         {% include 'left_side.html' %}

            <div class="col-lg-9">

                {% block profile %}
<!-- Start Categories of The Month -->
    <section class="container py-5">
        <div class="row text-center pt-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h1">Главная страница профиля</h1>
                <p>
                    Общая информация о профиле
                </p>
            </div>
        </div>
    </section>
    <!-- End Categories of The Month -->

                {% endblock %}

            </div>

        </div>
    </div>







{% endblock content %}

app/core/templates/core/tariffs.html
{% extends 'main.html' %}
{% load static %}

   {% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Покупка  абонемента</h1>
    <p class="lead"> Цены на абонементы для посещения тренажерного зала</p>
    <hr>
    </div>

            <div class="col-lg-10 container-fluid">
                <div class="row">

            {% for item in subscription %}
                    <div class="col-md-4">
                        <div class="card mb-4 product-wap rounded-0">
                            <div class="card-body" style="height: 102px">
                                 <p> {{ item.get_title_display }} </p>
                            </div>


                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal"> {{ item.description }} </h4>
                            </div>
                            <div class="card-body">
                                <h1 class="card-title pricing-card-title"><span>&#8381;</span> {{ item.price }} </h1>
                                <ul class="list-unstyled mt-3 mb-4">
                                </ul>

                                         {% if request.user.is_authenticated %}
                           <a href="{% url 'membership:add_membership' item.pk %}">
                               <button type="button" class="btn btn-sm btn-outline-secondary" > Купить </button>
                           </a>
                                <hr>
                                  {% else %}
                               <h2> Need registration to buy</h2>
                                  {% endif%}

                            </div>



                        </div>
                    </div>
            {% endfor %}

                </div>
            </div>









  {% endblock content %}