app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import register

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # главная страница сайта
    path('', include('core.urls')),
    # магазин
    path('store/', include('store.urls')),
    # сообщество - создание и просмотр постов
    path('community/', include('community.urls')),
    # покупка абонементов
    path('membership/', include('membership.urls')),


    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register, name='register'),
]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/community/urls.py
from django.urls import path

from community.views import *

app_name = 'community'

urlpatterns = [
    # главная страница fitlife community
    path('', main_page, name="main_page"),
    path('tags/<slug:tag_slug>/', TagIndexView.as_view(), name='post_by_tag'),
    path('post_detail/<post_pk>/', post_detail, name='post_detail'),
    path('create_post/', CreatePost.as_view(), name='create_post'),
    path('my_posts/', my_posts, name='my_posts'),
    path('delete_comment/<comm_pk>/', delete_comment, name='delete_comment'),
    path('delete_post/<post_pk>/', delete_post, name='delete_post'),
    path('edit_post/<int:pk>/', UpdatePost.as_view(), name='edit_post'),
    ]

app/core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [

    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('profile/', profile, name='profile'),
    path('tariffs/', tariffs, name='tariffs'),
    path('our_command/', our_command, name='our_command'),

]

app/membership/urls.py
from django.urls import path
from membership.views import *

app_name = 'membership'

urlpatterns = [

    # path('', index, name='index'),
    path('my_subscription/', my_subscription, name='my_subscription'),
    path('add_membership/<item_pk>/', add_membership, name='add_membership'),
    path('activation/<item_pk>/', activation, name='activation'),
    # path('deactivation/<item_pk>/', deactivation, name='deactivation'),
    path('delete_membership/<item_pk>/', delete_membership, name='delete_membership'),
    path('check_visit/<item_pk>/', check_visit, name='check_visit'),
]

app/store/urls.py
from django.urls import path

from store.views import *

app_name = 'store_app'

urlpatterns = [
    # главная страница магазина
    path('', store, name="store"),
    # страница, которая отображает содержимое страницы
    path('cart/', cart, name="cart"),
    # страница оформления заказа
    path('checkout/', checkout, name="checkout"),
    # ссылка на контроллер, который обрабатывает данные, полученные из функции "updateUserOrder" из файла cart.js
    path('update_item/', update_item, name="update_item"),
    #  ссылка на контроллер, который обрабатывает данные, полученные из функции "submitFormData" script checkout.html
    path('process_order/', process_order, name="process_order"),
    #
    path('my_orders/<int:order_id>/', my_orders, name='my_orders'),
    #
    path('purchase_archive/', purchase_archive, name='purchase_archive'),

]

app/templates/about.html
{% extends 'main.html' %}
{% load static %}

   {% block content %}

    <section class="bg-success py-5">
        <div class="container">
            <div class="row align-items-center py-1">
                <div class="col-md-8 text-white" style="padding: 1rem">
                    <h1>About Us</h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    </p>
                    <ul>
                        <li> item 1 </li>
                        <li> item 2 </li>
                        <li> item 3 </li>
                        <li> item 4 </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- Close Banner -->



    <!-- Start Content Page -->
    <div class="container-fluid" style="padding: 2rem">
        <div class="col-md-6 m-auto text-center">
            <h1 class="h1">Contact Us</h1>

                    <h2 class="h2 text-success border-bottom pb-3  logo">Fitlife company</h2>

                    <ul class="list-unstyled footer-link-list">
                        <li>
                        <i class="fas fa-map-marker-alt fa-fw"></i>
                            123 Consectetur at ligula 10660
                        </li>
                        <li>
                            <i class="fa fa-phone fa-fw"></i>
                            <a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-fw"></i>
                            <a class="text-decoration-none" href="mailto:info@company.com">fitlife@company.com</a>
                        </li>
                    </ul>

        </div>
    </div>




  {% endblock content %}

app/templates/footer.html
    {% load static %}
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="{% static 'img/fitlife.jpg' %}" alt="логотип bootstrap" height="100">
        <small class="d-block mb-3 text-muted">© 2022</small>
      </div>
      <div class="col-6 col-md">
        <h5>Покупка абонемента</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="{% url 'core:tariffs' %}">Тарифы</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Как связаться с нами</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="{% url 'core:contact' %}">Контакты</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>О нас</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="{% url 'core:our_command' %}">Команда</a></li>

        </ul>
      </div>
    </div>
  </footer>

app/templates/left_side.html
            <div class="col-lg-3">
                <h1>  <a  href="{% url 'core:profile' %}" class="h2 pb-4 text-dark text-decoration-none text-reset">Моя страница </a></h1>
                <ul class="list-unstyled templatemo-accordion">
                    <li class="pb-3">
                        <a class="collapsed d-flex justify-content-between h3 text-decoration-none" href="#">
                            Мои покупки
                            <i class="fa fa-fw fa-chevron-circle-down mt-1"></i>
                        </a>
                        <ul class="collapse show list-unstyled pl-3">
                            <li><a class="text-decoration-none" href="{% url 'store_app:purchase_archive' %}">Архив покупок</a></li>
                        </ul>
                    </li>
                    <li class="pb-3">
                        <a class="collapsed d-flex justify-content-between h3 text-decoration-none" href="#">
                            Fitlife community
                            <i class="pull-right fa fa-fw fa-chevron-circle-down mt-1"></i>
                        </a>
                        <ul id="collapseTwo" class="collapse list-unstyled pl-3">
                            <li><a class="text-decoration-none" href="{% url 'community:my_posts' %}">Показать мои посты</a></li>
                            <li><a class="text-decoration-none" href="{% url 'community:create_post' %}">Создать новый пост</a></li>

                        </ul>
                    </li>
                    <li class="pb-3">
                        <a class="collapsed d-flex justify-content-between h3 text-decoration-none" href="#">
                            Тарифы
                            <i class="pull-right fa fa-fw fa-chevron-circle-down mt-1"></i>
                        </a>
                        <ul id="collapseThree" class="collapse list-unstyled pl-3">
                            <li><a class="text-decoration-none" href="{% url 'membership:my_subscription' %}"> Мои абонементы</a></li>

                        </ul>
                    </li>
                </ul>
                <hr>
                <h1 class="h2 pb-4">Tags</h1>
                <p>
             {% for tag in most_comm_tags %}
                   <a class="btn btn-outline-success" href="{% url 'community:post_by_tag' tag.slug %}" role="button">{{ tag.name }}</a>
             {% endfor %}
                </p>
                <hr>
                 <a  class="btn btn-outline-secondary" href="{% url 'community:create_post' %}"> Создать пост </a>
                <a  class="btn btn-outline-secondary" href="{% url 'community:my_posts' %}"> Перейти в мои посты </a>

            </div>

app/templates/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Fitlife</title>



    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/x-icon" href=" {% static 'img/favicon.ico'%}">

    <link rel="stylesheet" href=" {% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href=" {% static 'css/templatemo.css'%}">
    <link rel="stylesheet" href=" {% static 'css/custom.css' %}">

    <!-- My custom styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">







    <script type="text/javascript">
		var user = '{{request.user}}'
        console.log(user)
	</script>
</head>

<body>
         {% include 'navbar.html' %}

         <div class="container">
            <br>
            {% block content %}
            {% endblock content %}


         {% include 'footer.html' %}


         </div>




    <!-- Start Script -->
    <script src=" {% static 'js/jquery-1.11.0.min.js'%}"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %} "></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %} "></script>
    <script src="{% static 'js/templatemo.js' %} "></script>
    <script src=" {% static 'js/custom.js'%}"></script>
    <!-- End Script -->


{#  Customer script   #}
   <script type="text/javascript" src="{% static 'js/cart.js' %}"> </script>
   <script type="text/javascript" src="{% static 'js/cookie_token.js' %}"> </script>

</body>
</html>

app/templates/navbar.html
    {% load static %}

 <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light shadow">
        <div class="container d-flex justify-content-between align-items-center">

            <a class="navbar-brand text-success logo h1 align-self-center" href="/">
     <img src="{% static 'img/fitlife.jpg' %}" alt="" width="100" height="50">
            </a>

            <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
             data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between"
                 id="templatemo_main_nav">
                <div class="flex-fill">
                    <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:about' %}">О клубе</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:tariffs' %}">Тарифы</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link" href="{% url 'store_app:store' %}">Магазин</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link" href="{% url 'community:main_page' %}">Fitlife community</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:contact' %}">Контакты</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar align-self-center d-flex">
{#                    <div class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3">#}
{#                        <div class="input-group">#}
{#                            <input type="text" class="form-control" id="inputMobileSearch" placeholder="Search ...">#}
{#                            <div class="input-group-text">#}
{#                                <i class="fa fa-fw fa-search"></i>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <a class="nav-icon d-none d-lg-inline" href="#" data-bs-toggle="modal" data-bs-target="#templatemo_search">#}
{#                        <i class="fa fa-fw fa-search text-dark mr-2"></i>#}
{#                    </a>#}
                    <a class="nav-icon position-relative text-decoration-none" href="{% url 'store_app:cart' %}">
                        <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>
                        <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark">
                            <span id="cart-total">{{ cart_items }}</span>
                            </span>
                    </a>
                                  {% if request.user.is_authenticated %}


                            <a class="nav-link" href="{% url "core:profile" %}">Моя страница</a>
                  <span style="padding: 10px; color: #333d4b">Welcome,  <strong style="text-transform: uppercase">{{ user.username }}</strong> </span>  <a href="{% url "logout" %}?next={% url 'core:index' %}" class="btn btn-outline-success"> Выход</a>
              {% else %}
                <a href="{% url "register" %}" class="btn btn-outline-success" style="margin-right: 3px"> Register </a>  <a href=" {% url "login" %}" class="btn btn-outline-success"> Login </a>
              {% endif%}

                </div>
            </div>

        </div>
    </nav>
    <!-- Close Header -->